/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiApiPublicConsentRejectRequest
 */
export interface ApiApiPublicConsentRejectRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicConsentRejectRequest
     */
    consentRequestId?: string | null;
}

/**
 * Check if a given object implements the ApiApiPublicConsentRejectRequest interface.
 */
export function instanceOfApiApiPublicConsentRejectRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicConsentRejectRequestFromJSON(json: any): ApiApiPublicConsentRejectRequest {
    return ApiApiPublicConsentRejectRequestFromJSONTyped(json, false);
}

export function ApiApiPublicConsentRejectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicConsentRejectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consentRequestId': !exists(json, 'consentRequestId') ? undefined : json['consentRequestId'],
    };
}

export function ApiApiPublicConsentRejectRequestToJSON(value?: ApiApiPublicConsentRejectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consentRequestId': value.consentRequestId,
    };
}

