/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiApiPublicConsentGetOneResponseScopeDto
 */
export interface ApiApiPublicConsentGetOneResponseScopeDto {
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicConsentGetOneResponseScopeDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicConsentGetOneResponseScopeDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicConsentGetOneResponseScopeDto
     */
    value?: string | null;
}

/**
 * Check if a given object implements the ApiApiPublicConsentGetOneResponseScopeDto interface.
 */
export function instanceOfApiApiPublicConsentGetOneResponseScopeDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicConsentGetOneResponseScopeDtoFromJSON(json: any): ApiApiPublicConsentGetOneResponseScopeDto {
    return ApiApiPublicConsentGetOneResponseScopeDtoFromJSONTyped(json, false);
}

export function ApiApiPublicConsentGetOneResponseScopeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicConsentGetOneResponseScopeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ApiApiPublicConsentGetOneResponseScopeDtoToJSON(value?: ApiApiPublicConsentGetOneResponseScopeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'value': value.value,
    };
}

